### ISSUE TITLE
Tracking Current Tasks

### ISSUE THREAD

**Issue by Fenrirthviti** [Fenrirthviti/Cockatrice#1]
Just so I can keep track of what I'm working on

- [x] vcpkg integration (i.e. why/where CMAKE_TOOLCHAIN_FILE is being used)
- [ ] build caching in CI
- [ ] Update Windows build directions wiki page
- [ ] Fix project not being debuggable in VS
- [x] Compile issue with all warnings
- [ ] Make cmake use git tags for versioning
- [ ] Don't include redists, just check when installing
- [ ] Fix empty folders copied during builds
- [x] Figure out wtf version_string.cpp/h is actually doing??????

**Comment by Fenrirthviti** [comment]
qt plugins required: 

- audio
- iconengines
- imageformats
- platforms
- printsupport
- sqldrivers
- styles
